import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import BackgroundShuffler from "./_components/backgroundShuffler";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white">
        <div className="relative h-screen w-screen">
          <BackgroundShuffler />
          <div className="relative z-10">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
